### PR TITLE
Added object or array path traversing.

### PR DESCRIPTION
**Pull request by srdjanmarjanovic**
"Click to expand. Double-click to show path."

_krumo_path.js_ file is borrowed from the usage of krumo as a part of  Devel Drupal module https://www.drupal.org/project/devel with the permission of original author Wouter van Dongen from DongIT

### CODE REVIEW

**Comment by mmucklo** [comment]
Is there a license to add if we take the krumo_path.js file?

**Comment by scottchiefbaker** [comment]
@srdjanmarjanovic do you have a public demo of this somewhere? I want to see how it looks on a real object.

**Comment by srdjanmarjanovic** [comment]
@mmucklo I contacted author of the original *krumo_path.js* for the permission. 
@scottchiefbaker I dont have a live demo, but it's looks something like this https://www.drupal.org/files/issues/krumo_path_2.png when you double click on the *safe_value* element

**Comment by srdjanmarjanovic** [comment]
Good news! I've got an email from the author, and he gave me permission to integrate his code into krumo. There is a blog post in which he made it publicly available for non Drupal projects using kurmo https://www.dongit.nl/tech/jquery-krumo-path-plugin.

Please note that this plugin does require jQuery to work

**Comment by mmucklo** [comment]
So will krumo now need jQuery?



On Apr 17, 2015, at 12:12 AM, Srdjan Marjanovic <notifications@github.com>
wrote:

Good news! I've got an email from the author, and he gave me permission to
integrate his code into krumo. There is a blog post in which he made it
publicly available for non Drupal projects using kurmo
https://www.dongit.nl/tech/jquery-krumo-path-plugin.

Please note that this plugin does require jQuery to work

—
Reply to this email directly or view it on GitHub
<https://github.com/oodle/krumo/pull/24#issuecomment-93928225>.

**Comment by srdjanmarjanovic** [comment]
Well, yes.

**Comment by scottchiefbaker** [comment]
Requiring JQuery for Krumo is probably going to be a show stopper. We've been trying to keep the library really lean. Requiring 90k of JQuery to be included every time just to show a path seems a little overkill.

Is it possible to rewrite this without requiring JQuery?

**Comment by mmucklo** [comment]
I second trying to remove jQuery as a dependency.

**Comment by scottchiefbaker** [comment]
Any word on this?

**Comment by kktsvetkov** [comment]
Perhaps this can be bundled into a separate package that will work along with this one. The separate package can introduce both jQuery and that extra JS file.

**Comment by mmucklo** [comment]
I’m wondering if there’s a way to do it without jQuery.

I remember reviewing this and initially my thought was no or that it would be difficult - but maybe on a second look...

**Comment by srdjanmarjanovic** [comment]
Haven't looked at that as i don't use krumo anymore.

**Comment by scottchiefbaker** [comment]
Requiring JQuery is not going to work. The entirety of the JS for Krumo is 3.6KB. JQuery is 86KB. We can't include 86K on every request for a single feature.

**Pull request closed without merging**
